### ISSUE TITLE
Fix Yoast SEO Compatibility problem

### ISSUE THREAD

**Issue by benjamintennant** [downshiftorg/prophoto7-issues#409]
When updating or publishing a post/page with an embedded gallery with Yoast SEO running, a PHP fatal error is triggered. The action processes, but the error is jarring. 

`Fatal error: Uncaught RuntimeException: ViewContext accessed before data set. in /kunden/457897_13347/foto/wordpress/wp-content/themes/prophoto7/src/php/front/Services/View/ViewContext.php:288 Stack trace: #0 /kunden/457897_13347/foto/wordpress/wp-content/themes/prophoto7/src/php/front/Services/View/ViewContext.php(165): ProPhoto\Front\Services\View\ViewContext->get(Array) #1 /kunden/457897_13347/foto/wordpress/wp-content/themes/prophoto7/src/php/front/View/ResolvesGalleryComponentsTrait.php(36): ProPhoto\Front\Services\View\ViewContext->getGalleryStyle('ebb7075c-30ef-4...') #2 /kunden/457897_13347/foto/wordpress/wp-content/themes/prophoto7/src/php/prophoto/Middleware/GalleryMiddleware.php(87): ProPhoto\Middleware\GalleryMiddleware->resolveGalleryStyle(Object(ProPhoto\Front\Services\View\ViewContext), 'ebb7075c-30ef-4...') #3 /kunden/457897_13347/foto/wordpress/wp-includes/shortcodes.php(319): ProPhoto\Middleware\GalleryMiddleware->renderGalleryFromShortCode(Array, '', 'pp_gallery') #4 [internal function]: do_shortcode_ta in /kunden/457897_13347/foto/wordpress/wp-content/themes/prophoto7/src/php/front/Services/View/ViewContext.php on line 288`

**Comment by benjamintennant** [comment]
+1 Tilman ticket 183581
