### ISSUE TITLE
Default WooCommerce layout applied to all page in VB

### ISSUE THREAD

**Issue by postmastersteve** [downshiftorg/prophoto7-issues#684]
Hello, I am getting an error while trying to edit my gallery pages and WordPress support team concluded that the problem was due to the ProPhoto Theme. Please help! 
Below is the last email from Wordpress support team. 
Thank you!

Hello Olesya,

Thank you for getting back to us.

I can understand your concern regarding this issue. I have logged in to admin panel of website at https://www.zestyorangephoto.com/wp-admin with provided login details and able to replicate issue with editing pages under Galleries ( Family, Maternity, Newborn ) . It is loading with 'Internal server error' .

I didn't find any recent error logs generated for this website at https://www1.ipage.com/controlpanel/cgiManagement/cgierrorlog.html . So, i have tried enabled debug mode for this Wordpress website inside wp-config.php file.

Now, when editing above 3 pages, it is displaying error: 
Fatal error: Uncaught RuntimeException: ViewContext accessed before data set. in /hermes/bosnaweb11a/b574/ipg.lesyasn/wp-content/themes/prophoto7/src/php/front/Services/View/ViewContext.php:288 Stack trace: #0 /hermes/bosnaweb11a/b574/ipg.lesyasn/wp-content/themes/prophoto7/src/php/front/Services/View/ViewContext.php(165): ProPhoto\Front\Services\View\ViewContext->get(Array) #1 /hermes/bosnaweb11a/b574/ipg.lesyasn/wp-content/themes/prophoto7/src/php/front/View/ResolvesGalleryComponentsTrait.php(36): ProPhoto\Front\Services\View\ViewContext->getGalleryStyle(NULL) #2 /hermes/bosnaweb11a/b574/ipg.lesyasn/wp-content/themes/prophoto7/src/php/prophoto/Middleware/GalleryMiddleware.php(123): ProPhoto\Middleware\GalleryMiddleware->resolveGalleryStyle(Object(ProPhoto\Front\Services\View\ViewContext), NULL) #3 /hermes/bosnaweb11a/b574/ipg.lesyasn/wp-includes/shortcodes.php(319): ProPhoto\Middleware\GalleryMiddleware->renderGalleryFromShortCode(Array, '', 'pp_gallery') #4 [internal function]: do_shortcode_tag(Array) #5 /hermes/bosnaw in /hermes/bosnaweb11a/b574/ipg.lesyasn/wp-content/themes/prophoto7/src/php/front/Services/View/ViewContext.php on line 288

These errors are related to theme 'prophoto7' set for this website. I recommend you to contact theme support regarding this issue. URL at https://www.zestyorangephoto.com/info.php shows PHP settings enabled for your account.

Please feel free to reply to this email if you have any further questions, we are happy to help you.

Sincerely,

Suresh K 
Senior Technical Specialist

**Comment by postmastersteve** [comment]
+1 Karen Ketels ticket 191535
