### ISSUE TITLE
After 7.7.17 auto update - all pages error

### ISSUE THREAD

**Issue by phillipburger** [downshiftorg/prophoto7-issues#802]
I logged in to help a client on her site and then i saw the theme auto-update. All of a sudden, all front end pages are down with this error:

`Fatal error: Uncaught Error: Call to undefined function wp_body_open() in /home2/xxxxxx/public_html/wp-content/themes/prophoto7/views/front/body_open.php:2 Stack trace: #0 /home2/xxxxxx/public_html/wp-content/themes/prophoto7/src/php/prophoto/Infrastructure/View/View.php(92): include() #1 /home2/xxxxxx/public_html/wp-content/themes/prophoto7/src/php/prophoto/Infrastructure/View/Site/Head/BodyOpenView.php(61): ProPhoto\Infrastructure\View\View->render() #2 /home2/xxxxxx/public_html/wp-content/themes/prophoto7/src/php/prophoto/Infrastructure/View/View.php(153): ProPhoto\Infrastructure\View\Site\Head\BodyOpenView->render('front/body_open', Array) #3 /home2/xxxxxx/public_html/wp-content/themes/prophoto7/src/php/prophoto/Infrastructure/View/View.php(84): ProPhoto\Infrastructure\View\View->markup('front/body_open', Array) #4 /home2/xxxxxx/public_html/wp-content/themes/prophoto7/src/php/prophoto/Infrastructure/View/Site/Head/HeadView.php(74): ProPhoto\Infrastructure\View\View->render() #5 /home2/xxxxxx/public_html/ in /home2/xxxxxx/public_html/wp-content/themes/prophoto7/views/front/body_open.php on line 2`

Not sure what to try next....

**Comment by phillipburger** [comment]
I seem to have fixed this by upgrading WordPress which was a very old version - but it might be helpful to add some error checking for WordPress version instead of just failing with this message.
